In [1]:
import os
import pandas as pd
os.chdir('../../../')

from operations.api import KGFarm
kgfarm = KGFarm()

(KGFarm is running in Human in the loop mode)
Connected to Stardog!
Access the Stardog UI at: https://cloud.stardog.com/

In [2]:
entity_df = pd.read_csv(r'C:\Users\niki_\Google Drive\GRAD SCHOOL\Papers\KGFarm-LFE\Regression\energydata_complete.csv')
entity_df

,date,Appliances,lights,T1,RH_1,T2,RH_2,T3,RH_3,T4,RH_4,T5,RH_5,T6,RH_6,T7,RH_7,T8,RH_8,T9,RH_9,T_out,Press_mm_hg,RH_out,Windspeed,Visibility,Tdewpoint,rv1,rv2
0,2016-01-11 17:00:00,60,30,19.890000,47.596667,19.200000,44.790000,19.790000,44.730000,19.000000,45.566667,17.166667,55.200000,7.026667,84.256667,17.200000,41.626667,18.2000,48.900000,17.033333,45.5300,6.600000,733.5,92.000000,7.000000,63.000000,5.300000,13.275433,13.275433
1,2016-01-11 17:10:00,60,30,19.890000,46.693333,19.200000,44.722500,19.790000,44.790000,19.000000,45.992500,17.166667,55.200000,6.833333,84.063333,17.200000,41.560000,18.2000,48.863333,17.066667,45.5600,6.483333,733.6,92.000000,6.666667,59.166667,5.200000,18.606195,18.606195
2,2016-01-11 17:20:00,50,30,19.890000,46.300000,19.200000,44.626667,19.790000,44.933333,18.926667,45.890000,17.166667,55.090000,6.560000,83.156667,17.200000,41.433333,18.2000,48.730000,17.000000,45.5000,6.366667,733.7,92.000000,6.333333,55.333333,5.100000,28.642668,28.642668
3,2016-01-11 17:30:00,50,40,19.890000,46.066667,19.200000,44.590000,19.790000,45.000000,18.890000,45.723333,17.166667,55.090000,6.433333,83.423333,17.133333,41.290000,18.1000,48.590000,17.000000,45.4000,6.250000,733.8,92.000000,6.000000,51.500000,5.000000,45.410389,45.410389
4,2016-01-11 17:40:00,60,40,19.890000,46.333333,19.200000,44.530000,19.790000,45.000000,18.890000,45.530000,17.200000,55.090000,6.366667,84.893333,17.200000,41.230000,18.1000,48.590000,17.000000,45.4000,6.133333,733.9,92.000000,5.666667,47.666667,4.900000,10.084097,10.084097
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19730,2016-05-27 17:20:00,100,0,25.566667,46.560000,25.890000,42.025714,27.200000,41.163333,24.700000,45.590000,23.200000,52.400000,24.796667,1.000000,24.500000,44.500000,24.7000,50.074000,23.200000,46.7900,22.733333,755.2,55.666667,3.333333,23.666667,13.333333,43.096812,43.096812
19731,2016-05-27 17:30:00,90,0,25.500000,46.500000,25.754000,42.080000,27.133333,41.223333,24.700000,45.590000,23.230000,52.326667,24.196667,1.000000,24.557143,44.414286,24.7000,49.790000,23.200000,46.7900,22.600000,755.2,56.000000,3.500000,24.500000,13.300000,49.282940,49.282940
19732,2016-05-27 17:40:00,270,10,25.500000,46.596667,25.628571,42.768571,27.050000,41.690000,24.700000,45.730000,23.230000,52.266667,23.626667,1.000000,24.540000,44.400000,24.7000,49.660000,23.200000,46.7900,22.466667,755.2,56.333333,3.666667,25.333333,13.266667,29.199117,29.199117
19733,2016-05-27 17:50:00,420,10,25.500000,46.990000,25.414000,43.036000,26.890000,41.290000,24.700000,45.790000,23.200000,52.200000,22.433333,1.000000,24.500000,44.295714,24.6625,49.518750,23.200000,46.8175,22.333333,755.2,56.666667,3.833333,26.166667,13.233333,6.322784,6.322784
19734,2016-05-27 18:00:00,430,10,25.500000,46.600000,25.264286,42.971429,26.823333,41.156667,24.700000,45.963333,23.200000,52.200000,21.026667,1.000000,24.500000,44.054000,24.7360,49.736000,23.200000,46.8450,22.200000,755.2,57.000000,4.000000,27.000000,13.200000,34.118851,34.118851

In [ ]:
kgfarm.recommend_cleaning_operations(entity_df)

In [ ]:
entity_df = kgfarm.clean(entity_df,'fill')
entity_df

In [ ]:
entity_df

# Without transformation

In [3]:
dependent_variable = "Appliances"
independent_variables = [feature for feature in list(entity_df.columns) if feature != dependent_variable]

X = entity_df[independent_variables]
y = entity_df[dependent_variable]

In [4]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

### To convert date to float

In [5]:
tranformation_info = kgfarm.recommend_feature_transformations(X_train)
tranformation_info

Processing unseen data

,Transformation,Package,Library,Feature,Transformation_type
0,MinMaxScaler,preprocessing,sklearn,"[T2, T4, Press_mm_hg, T6, RH_6, T7, T_out, T9]",Normalization
1,LabelEncoder,preprocessing,sklearn,[date],Ordinal encoding
2,StandardScaler,preprocessing,sklearn,"[rv1, Tdewpoint, Visibility, Windspeed, RH_9, lights, rv2, RH_5, RH_4, RH_3, RH_2, RH_1, RH_8, RH_7]",Scaling

In [6]:
X_train, _ = kgfarm.apply_transformation(tranformation_info.iloc[1], X_train)
X_train
X_test, _ = kgfarm.apply_transformation(tranformation_info.iloc[1], X_test)
X_test

Applying LabelEncoder transformation
1 feature(s) ['date'] transformed successfully!
Applying LabelEncoder transformation
1 feature(s) ['date'] transformed successfully!

,date,lights,T1,RH_1,T2,RH_2,T3,RH_3,T4,RH_4,T5,RH_5,T6,RH_6,T7,RH_7,T8,RH_8,T9,RH_9,T_out,Press_mm_hg,RH_out,Windspeed,Visibility,Tdewpoint,rv1,rv2
15563,6198,0,21.200000,33.290,19.823333,31.790000,23.463333,38.230000,20.50,31.730000,19.200000,39.363333,10.263333,1.000000,19.790000,24.290000,21.890000,34.466667,18.790000,29.230000,9.850000,756.183333,41.833333,4.833333,40.000000,-2.666667,42.017180,42.017180
12564,5005,0,21.790000,38.500,19.500000,40.633333,22.500000,37.900000,21.00,37.900000,20.033333,47.290000,7.000000,40.333333,21.323333,35.030000,22.290000,37.526667,20.600000,40.326667,6.900000,754.000000,75.000000,4.000000,40.000000,2.800000,24.624380,24.624380
10649,4238,0,22.390000,41.390,20.200000,43.790000,24.500000,39.333333,20.10,38.260000,19.390000,48.090000,11.030000,41.526667,21.200000,34.156667,22.290000,41.260000,19.760000,42.060000,10.100000,756.433333,68.000000,5.833333,40.000000,4.450000,3.731260,3.731260
16554,6594,0,24.000000,30.260,24.390000,26.963333,23.390000,33.400000,22.79,31.200000,21.033333,40.626667,20.390000,1.000000,22.832857,26.738571,23.272000,34.480000,20.790000,35.500000,19.100000,760.000000,31.000000,4.000000,40.000000,1.500000,1.058826,1.058826
8130,3233,0,20.050000,38.245,17.600000,41.000000,21.100000,37.200000,19.89,36.400000,18.200000,43.560000,0.133333,78.493333,18.390000,36.000000,20.200000,45.433333,17.500000,38.863333,0.100000,754.600000,99.000000,1.000000,32.000000,-0.100000,39.248108,39.248108
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12861,5111,0,22.066667,40.760,19.500000,44.000000,22.890000,39.700000,20.50,38.590000,20.000000,46.700000,7.000000,56.490000,21.700000,36.933333,22.832857,41.095714,20.100000,40.930000,6.850000,750.950000,95.000000,1.500000,34.500000,6.050000,13.786652,13.786652
14687,5834,0,22.823333,36.530,22.600000,34.560000,27.463333,38.193333,22.89,34.471429,20.730000,42.000000,15.130000,1.000000,21.934000,30.560000,23.290000,38.590000,20.600000,37.966667,13.250000,757.683333,57.500000,6.000000,40.000000,4.950000,14.309959,14.309959
16295,6498,0,23.100000,34.200,21.600000,33.663333,23.100000,36.000000,22.76,33.560000,21.856667,63.666667,7.826667,2.966667,21.600000,29.332000,24.290000,36.656667,20.290000,33.764286,10.383333,765.366667,57.500000,2.333333,40.000000,2.250000,28.423231,28.423231
3369,1332,0,21.600000,42.530,20.790000,41.826667,22.500000,43.790000,20.39,42.000000,19.000000,58.696667,1.600000,90.263333,18.600000,38.163333,22.200000,47.938333,18.323333,47.626667,2.100000,765.900000,90.000000,3.000000,25.500000,0.650000,31.507612,31.507612
14615,5809,0,22.290000,37.200,20.100000,39.126667,23.500000,37.790000,22.70,35.000000,20.390000,43.290000,9.926667,14.193333,21.952857,36.352857,22.390000,43.500000,20.356667,40.200000,9.833333,759.833333,67.333333,4.000000,30.833333,4.000000,34.287190,34.287190

In [ ]:
from sklearn.linear_model import RidgeCV
ridge_cv_model = RidgeCV(alphas=(0.1, 1.0, 10.0),scoring='neg_mean_absolute_error')
ridge_cv_model.fit(X_train,y_train)
y_pred = ridge_cv_model.predict(X_test)

In [7]:
from sklearn.linear_model import Ridge
model = Ridge(alpha=1)

In [8]:
model.fit(X_train,y_train)
y_pred = model.predict(X_test)

In [9]:
import numpy as np
from sklearn.metrics import mean_absolute_error, mean_squared_error
MAE = mean_absolute_error(y_test,y_pred)
MAE

57.19774887802003

In [10]:
MSE = mean_squared_error(y_test,y_pred)
RMSE = np.sqrt(MSE)
RMSE

95.95885982134087

# With transformation

In [11]:
X_transformed = entity_df[independent_variables]
y = entity_df[dependent_variable]

### Split train-test data

In [12]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_transformed, y, test_size=0.3, random_state=0)

### Transformation suggestions based on the training set

In [13]:
tranformation_info = kgfarm.recommend_feature_transformations(X_train)
tranformation_info

Processing unseen data

,Transformation,Package,Library,Feature,Transformation_type
0,MinMaxScaler,preprocessing,sklearn,"[T2, T4, Press_mm_hg, T6, RH_6, T7, T_out, T9]",Normalization
1,LabelEncoder,preprocessing,sklearn,[date],Ordinal encoding
2,StandardScaler,preprocessing,sklearn,"[rv1, Tdewpoint, Visibility, Windspeed, RH_9, lights, rv2, RH_5, RH_4, RH_3, RH_2, RH_1, RH_8, RH_7]",Scaling

### Transformation for Training set

In [14]:
X_train, _ = kgfarm.apply_transformation(tranformation_info.iloc[0], X_train)
X_train

Applying MinMaxScaler transformation
8 feature(s) ['T2', 'T4', 'Press_mm_hg', 'T6', 'RH_6', 'T7', 'T_out', 'T9'] transformed successfully!

,date,lights,T1,RH_1,T2,RH_2,T3,RH_3,T4,RH_4,T5,RH_5,T6,RH_6,T7,RH_7,T8,RH_8,T9,RH_9,T_out,Press_mm_hg,RH_out,Windspeed,Visibility,Tdewpoint,rv1,rv2
19651,2016-05-27 04:10:00,0,24.000000,44.900000,0.452041,45.400000,26.700000,40.290000,0.846847,42.200000,22.39,56.200000,0.568428,0.370408,0.833228,45.290000,24.290000,49.900000,0.812695,46.090000,0.596711,0.609236,87.500000,3.666667,51.666667,11.450000,36.528125,36.528125
11529,2016-03-31 18:30:00,0,21.700000,43.423333,0.275503,43.963333,22.000000,38.363333,0.498498,40.566667,20.10,48.300000,0.423155,0.551239,0.454918,33.663333,24.500000,39.230000,0.531738,38.300000,0.427243,0.588281,78.500000,2.500000,34.500000,4.750000,7.183265,7.183265
5018,2016-02-15 13:20:00,10,20.365000,39.350000,0.231888,38.163333,21.633333,39.626667,0.369369,36.700000,17.70,50.790000,0.352496,0.546967,0.410467,30.133333,21.100000,36.290000,0.323621,38.963333,0.326421,0.714009,61.333333,7.666667,40.000000,-1.733333,3.668685,3.668685
16912,2016-05-08 03:40:00,0,24.390000,39.090000,0.472498,40.030000,25.700000,38.790000,0.810811,37.530000,22.29,50.400000,0.585255,0.265737,0.794451,40.567500,24.600000,43.696000,0.800208,44.200000,0.563461,0.520761,85.333333,2.000000,27.666667,10.100000,25.725311,25.725311
14051,2016-04-18 06:50:00,0,21.260000,38.826667,0.109038,44.260000,22.200000,36.400000,0.594595,35.500000,20.20,44.700000,0.178480,0.525379,0.498660,30.852500,22.000000,38.626667,0.572320,39.300000,0.170361,0.738456,97.833333,2.000000,61.166667,0.000000,16.478583,16.478583
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13123,2016-04-11 20:10:00,30,22.790000,44.700000,0.399806,43.500000,23.100000,40.790000,0.656757,43.066667,21.20,47.928571,0.574152,0.219380,0.625158,37.566667,23.890000,43.071429,0.628165,41.730000,0.601537,0.492045,80.500000,0.666667,40.000000,10.416667,33.159902,33.159902
19648,2016-05-27 03:40:00,0,24.033333,44.860000,0.457233,45.290000,26.700000,40.245000,0.846847,42.200000,22.39,56.433333,0.572406,0.371756,0.833228,45.442857,24.290000,49.966667,0.812695,46.000000,0.602074,0.611564,85.333333,3.000000,55.666667,11.266667,24.197280,24.197280
9845,2016-03-20 01:50:00,0,21.666667,36.090000,0.210807,38.863333,22.033333,35.933333,0.483183,34.863333,18.50,44.400000,0.341192,0.490698,0.368852,30.700000,22.290000,42.290000,0.468262,39.090000,0.330175,0.767559,80.333333,3.000000,23.000000,2.150000,29.956511,29.956511
10799,2016-03-26 16:50:00,0,21.890000,41.900000,0.340926,42.500000,23.200000,38.290000,0.467568,42.400000,19.89,51.433333,0.614030,0.369329,0.536885,37.260000,23.000000,42.590000,0.531738,42.230000,0.596174,0.528910,71.500000,6.333333,40.000000,8.366667,38.867774,38.867774
2732,2016-01-30 16:20:00,0,20.890000,43.760000,0.327114,42.760000,20.290000,44.663333,0.341441,45.060000,17.70,61.450556,0.348275,1.000000,0.140815,41.669444,19.873333,50.051111,0.152619,46.656667,0.359671,0.537835,81.333333,6.000000,40.000000,3.233333,6.640901,6.640901

In [15]:
X_train, _ = kgfarm.apply_transformation(tranformation_info.iloc[1], X_train)
X_train

Applying LabelEncoder transformation
1 feature(s) ['date'] transformed successfully!

,date,lights,T1,RH_1,T2,RH_2,T3,RH_3,T4,RH_4,T5,RH_5,T6,RH_6,T7,RH_7,T8,RH_8,T9,RH_9,T_out,Press_mm_hg,RH_out,Windspeed,Visibility,Tdewpoint,rv1,rv2
19651,11794,0,24.000000,44.900000,0.452041,45.400000,26.700000,40.290000,0.846847,42.200000,22.39,56.200000,0.568428,0.370408,0.833228,45.290000,24.290000,49.900000,0.812695,46.090000,0.596711,0.609236,87.500000,3.666667,51.666667,11.450000,36.528125,36.528125
11529,6948,0,21.700000,43.423333,0.275503,43.963333,22.000000,38.363333,0.498498,40.566667,20.10,48.300000,0.423155,0.551239,0.454918,33.663333,24.500000,39.230000,0.531738,38.300000,0.427243,0.588281,78.500000,2.500000,34.500000,4.750000,7.183265,7.183265
5018,3067,10,20.365000,39.350000,0.231888,38.163333,21.633333,39.626667,0.369369,36.700000,17.70,50.790000,0.352496,0.546967,0.410467,30.133333,21.100000,36.290000,0.323621,38.963333,0.326421,0.714009,61.333333,7.666667,40.000000,-1.733333,3.668685,3.668685
16912,10176,0,24.390000,39.090000,0.472498,40.030000,25.700000,38.790000,0.810811,37.530000,22.29,50.400000,0.585255,0.265737,0.794451,40.567500,24.600000,43.696000,0.800208,44.200000,0.563461,0.520761,85.333333,2.000000,27.666667,10.100000,25.725311,25.725311
14051,8464,0,21.260000,38.826667,0.109038,44.260000,22.200000,36.400000,0.594595,35.500000,20.20,44.700000,0.178480,0.525379,0.498660,30.852500,22.000000,38.626667,0.572320,39.300000,0.170361,0.738456,97.833333,2.000000,61.166667,0.000000,16.478583,16.478583
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13123,7894,30,22.790000,44.700000,0.399806,43.500000,23.100000,40.790000,0.656757,43.066667,21.20,47.928571,0.574152,0.219380,0.625158,37.566667,23.890000,43.071429,0.628165,41.730000,0.601537,0.492045,80.500000,0.666667,40.000000,10.416667,33.159902,33.159902
19648,11793,0,24.033333,44.860000,0.457233,45.290000,26.700000,40.245000,0.846847,42.200000,22.39,56.433333,0.572406,0.371756,0.833228,45.442857,24.290000,49.966667,0.812695,46.000000,0.602074,0.611564,85.333333,3.000000,55.666667,11.266667,24.197280,24.197280
9845,5897,0,21.666667,36.090000,0.210807,38.863333,22.033333,35.933333,0.483183,34.863333,18.50,44.400000,0.341192,0.490698,0.368852,30.700000,22.290000,42.290000,0.468262,39.090000,0.330175,0.767559,80.333333,3.000000,23.000000,2.150000,29.956511,29.956511
10799,6496,0,21.890000,41.900000,0.340926,42.500000,23.200000,38.290000,0.467568,42.400000,19.89,51.433333,0.614030,0.369329,0.536885,37.260000,23.000000,42.590000,0.531738,42.230000,0.596174,0.528910,71.500000,6.333333,40.000000,8.366667,38.867774,38.867774
2732,1654,0,20.890000,43.760000,0.327114,42.760000,20.290000,44.663333,0.341441,45.060000,17.70,61.450556,0.348275,1.000000,0.140815,41.669444,19.873333,50.051111,0.152619,46.656667,0.359671,0.537835,81.333333,6.000000,40.000000,3.233333,6.640901,6.640901

In [16]:
X_train, _ = kgfarm.apply_transformation(tranformation_info.iloc[2], X_train)
X_train

Applying StandardScaler transformation
14 feature(s) ['rv1', 'Tdewpoint', 'Visibility', 'Windspeed', 'RH_9', 'lights', 'rv2', 'RH_5', 'RH_4', 'RH_3', 'RH_2', 'RH_1', 'RH_8', 'RH_7'] transformed successfully!

,date,lights,T1,RH_1,T2,RH_2,T3,RH_3,T4,RH_4,T5,RH_5,T6,RH_6,T7,RH_7,T8,RH_8,T9,RH_9,T_out,Press_mm_hg,RH_out,Windspeed,Visibility,Tdewpoint,rv1,rv2
19651,11794,-0.485092,24.000000,1.162385,0.452041,1.224762,26.700000,0.314250,0.846847,0.727369,22.39,0.580960,0.568428,0.370408,0.833228,1.936079,24.290000,1.331279,0.812695,1.093921,0.596711,0.609236,87.500000,-0.151612,1.131210,1.837819,0.790940,0.790940
11529,6948,-0.485092,21.700000,0.790360,0.275503,0.869363,22.000000,-0.280578,0.498498,0.348864,20.10,-0.300300,0.423155,0.551239,0.454918,-0.348528,24.500000,-0.719063,0.531738,-0.788495,0.427243,0.588281,78.500000,-0.628264,-0.325483,0.233162,-1.220410,-1.220410
5018,3067,0.767957,20.365000,-0.235857,0.231888,-0.565430,21.633333,0.109456,0.369369,-0.547187,17.70,-0.022536,0.352496,0.546967,0.410467,-1.042164,21.100000,-1.284012,0.323621,-0.628203,0.326421,0.714009,61.333333,1.482624,0.141224,-1.319603,-1.461306,-1.461306
16912,10176,-0.485092,24.390000,-0.301360,0.472498,-0.103658,25.700000,-0.148852,0.810811,-0.354845,22.29,-0.066041,0.585255,0.265737,0.794451,1.008121,24.600000,0.139121,0.800208,0.637212,0.563461,0.520761,85.333333,-0.832543,-0.905332,1.514492,0.050496,0.050496
14051,8464,-0.485092,21.260000,-0.367703,0.109038,0.942751,22.200000,-0.886727,0.594595,-0.825271,20.20,-0.701887,0.178480,0.525379,0.498660,-0.900849,22.000000,-0.835000,0.572320,-0.546849,0.170361,0.738456,97.833333,-0.832543,1.937341,-0.904468,-0.583292,-0.583292
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13123,7894,3.274056,22.790000,1.111998,0.399806,0.754744,23.100000,0.468617,0.656757,0.928208,21.20,-0.341734,0.574152,0.219380,0.625158,0.418466,23.890000,0.019104,0.628165,0.040348,0.601537,0.492045,80.500000,-1.377288,0.141224,1.590334,0.560076,0.560076
19648,11793,-0.485092,24.033333,1.152307,0.457233,1.197551,26.700000,0.300357,0.846847,0.727369,22.39,0.606989,0.572406,0.371756,0.833228,1.966115,24.290000,1.344089,0.812695,1.072173,0.602074,0.611564,85.333333,-0.423984,1.470634,1.793910,-0.054238,-0.054238
9845,5897,-0.485092,21.666667,-1.057166,0.210807,-0.392266,22.033333,-1.030803,0.483183,-0.972811,18.50,-0.735352,0.341192,0.490698,0.368852,-0.930815,22.290000,-0.131055,0.468262,-0.597595,0.330175,0.767559,80.333333,-0.423984,-1.301326,-0.389541,0.340510,0.340510
10799,6496,-0.485092,21.890000,0.406579,0.340926,0.507366,23.200000,-0.303219,0.467568,0.773716,19.89,0.049229,0.614030,0.369329,0.536885,0.358206,23.000000,-0.073408,0.531738,0.161171,0.596174,0.528910,71.500000,0.937879,0.141224,1.099357,0.951304,0.951304
2732,1654,-0.485092,20.890000,0.875178,0.327114,0.571684,20.290000,1.664448,0.341441,1.390138,17.70,1.166669,0.348275,1.000000,0.140815,1.224650,19.873333,1.360316,0.152619,1.230853,0.359671,0.537835,81.333333,0.801692,0.141224,-0.130081,-1.257585,-1.257585

### Transformation on Testing set

In [17]:
X_test, _ = kgfarm.apply_transformation(tranformation_info.iloc[0], X_test)
X_test

Applying MinMaxScaler transformation
8 feature(s) ['T2', 'T4', 'Press_mm_hg', 'T6', 'RH_6', 'T7', 'T_out', 'T9'] transformed successfully!

,date,lights,T1,RH_1,T2,RH_2,T3,RH_3,T4,RH_4,T5,RH_5,T6,RH_6,T7,RH_7,T8,RH_8,T9,RH_9,T_out,Press_mm_hg,RH_out,Windspeed,Visibility,Tdewpoint,rv1,rv2
15563,2016-04-28 18:50:00,0,21.200000,33.290,0.274447,31.790000,23.463333,38.230000,0.489130,31.730000,19.200000,39.363333,0.476386,0.000000,0.414366,24.290000,21.890000,34.466667,0.405827,29.230000,0.478518,0.625194,41.833333,4.833333,40.000000,-2.666667,42.017180,42.017180
12564,2016-04-07 23:00:00,0,21.790000,38.500,0.250614,40.633333,22.500000,37.900000,0.534420,37.900000,20.033333,47.290000,0.380855,0.397708,0.558967,35.030000,22.290000,37.526667,0.594173,40.326667,0.383459,0.574419,75.000000,4.000000,40.000000,2.800000,24.624380,24.624380
10649,2016-03-25 15:50:00,0,22.390000,41.390,0.302211,43.790000,24.500000,39.333333,0.452899,38.260000,19.390000,48.090000,0.498829,0.409774,0.547336,34.156667,22.290000,41.260000,0.506764,42.060000,0.486574,0.631008,68.000000,5.833333,40.000000,4.450000,3.731260,3.731260
16554,2016-05-05 16:00:00,0,24.000000,30.260,0.611057,26.963333,23.390000,33.400000,0.696558,31.200000,21.033333,40.626667,0.772834,0.000000,0.701323,26.738571,23.272000,34.480000,0.613944,35.500000,0.776584,0.713953,31.000000,4.000000,40.000000,1.500000,1.058826,1.058826
8130,2016-03-08 04:00:00,0,20.050000,38.245,0.110565,41.000000,21.100000,37.200000,0.433877,36.400000,18.200000,43.560000,0.179840,0.783552,0.282339,36.000000,20.200000,45.433333,0.271592,38.863333,0.164339,0.588372,99.000000,1.000000,32.000000,-0.100000,39.248108,39.248108
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12861,2016-04-10 00:30:00,0,22.066667,40.760,0.250614,44.000000,22.890000,39.700000,0.489130,38.590000,20.000000,46.700000,0.380855,0.561072,0.594488,36.933333,22.832857,41.095714,0.542144,40.930000,0.381847,0.503488,95.000000,1.500000,34.500000,6.050000,13.786652,13.786652
14687,2016-04-22 16:50:00,0,22.823333,36.530,0.479115,34.560000,27.463333,38.193333,0.705616,34.471429,20.730000,42.000000,0.618852,0.000000,0.616556,30.560000,23.290000,38.590000,0.594173,37.966667,0.588077,0.660078,57.500000,6.000000,40.000000,4.950000,14.309959,14.309959
16295,2016-05-03 20:50:00,0,23.100000,34.200,0.405405,33.663333,23.100000,36.000000,0.693841,33.560000,21.856667,63.666667,0.405055,0.019885,0.585058,29.332000,24.290000,36.656667,0.561915,33.764286,0.495704,0.838760,57.500000,2.333333,40.000000,2.250000,28.423231,28.423231
3369,2016-02-04 02:30:00,0,21.600000,42.530,0.345700,41.826667,22.500000,43.790000,0.479167,42.000000,19.000000,58.696667,0.222775,0.902562,0.302143,38.163333,22.200000,47.938333,0.357267,47.626667,0.228786,0.851163,90.000000,3.000000,25.500000,0.650000,31.507612,31.507612
14615,2016-04-22 04:50:00,0,22.290000,37.200,0.294840,39.126667,23.500000,37.790000,0.688406,35.000000,20.390000,43.290000,0.466530,0.133401,0.618334,36.352857,22.390000,43.500000,0.568852,40.200000,0.477981,0.710078,67.333333,4.000000,30.833333,4.000000,34.287190,34.287190

In [18]:
X_test, _ = kgfarm.apply_transformation(tranformation_info.iloc[1], X_test)
X_test

Applying LabelEncoder transformation
1 feature(s) ['date'] transformed successfully!

,date,lights,T1,RH_1,T2,RH_2,T3,RH_3,T4,RH_4,T5,RH_5,T6,RH_6,T7,RH_7,T8,RH_8,T9,RH_9,T_out,Press_mm_hg,RH_out,Windspeed,Visibility,Tdewpoint,rv1,rv2
15563,6198,0,21.200000,33.290,0.274447,31.790000,23.463333,38.230000,0.489130,31.730000,19.200000,39.363333,0.476386,0.000000,0.414366,24.290000,21.890000,34.466667,0.405827,29.230000,0.478518,0.625194,41.833333,4.833333,40.000000,-2.666667,42.017180,42.017180
12564,5005,0,21.790000,38.500,0.250614,40.633333,22.500000,37.900000,0.534420,37.900000,20.033333,47.290000,0.380855,0.397708,0.558967,35.030000,22.290000,37.526667,0.594173,40.326667,0.383459,0.574419,75.000000,4.000000,40.000000,2.800000,24.624380,24.624380
10649,4238,0,22.390000,41.390,0.302211,43.790000,24.500000,39.333333,0.452899,38.260000,19.390000,48.090000,0.498829,0.409774,0.547336,34.156667,22.290000,41.260000,0.506764,42.060000,0.486574,0.631008,68.000000,5.833333,40.000000,4.450000,3.731260,3.731260
16554,6594,0,24.000000,30.260,0.611057,26.963333,23.390000,33.400000,0.696558,31.200000,21.033333,40.626667,0.772834,0.000000,0.701323,26.738571,23.272000,34.480000,0.613944,35.500000,0.776584,0.713953,31.000000,4.000000,40.000000,1.500000,1.058826,1.058826
8130,3233,0,20.050000,38.245,0.110565,41.000000,21.100000,37.200000,0.433877,36.400000,18.200000,43.560000,0.179840,0.783552,0.282339,36.000000,20.200000,45.433333,0.271592,38.863333,0.164339,0.588372,99.000000,1.000000,32.000000,-0.100000,39.248108,39.248108
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12861,5111,0,22.066667,40.760,0.250614,44.000000,22.890000,39.700000,0.489130,38.590000,20.000000,46.700000,0.380855,0.561072,0.594488,36.933333,22.832857,41.095714,0.542144,40.930000,0.381847,0.503488,95.000000,1.500000,34.500000,6.050000,13.786652,13.786652
14687,5834,0,22.823333,36.530,0.479115,34.560000,27.463333,38.193333,0.705616,34.471429,20.730000,42.000000,0.618852,0.000000,0.616556,30.560000,23.290000,38.590000,0.594173,37.966667,0.588077,0.660078,57.500000,6.000000,40.000000,4.950000,14.309959,14.309959
16295,6498,0,23.100000,34.200,0.405405,33.663333,23.100000,36.000000,0.693841,33.560000,21.856667,63.666667,0.405055,0.019885,0.585058,29.332000,24.290000,36.656667,0.561915,33.764286,0.495704,0.838760,57.500000,2.333333,40.000000,2.250000,28.423231,28.423231
3369,1332,0,21.600000,42.530,0.345700,41.826667,22.500000,43.790000,0.479167,42.000000,19.000000,58.696667,0.222775,0.902562,0.302143,38.163333,22.200000,47.938333,0.357267,47.626667,0.228786,0.851163,90.000000,3.000000,25.500000,0.650000,31.507612,31.507612
14615,5809,0,22.290000,37.200,0.294840,39.126667,23.500000,37.790000,0.688406,35.000000,20.390000,43.290000,0.466530,0.133401,0.618334,36.352857,22.390000,43.500000,0.568852,40.200000,0.477981,0.710078,67.333333,4.000000,30.833333,4.000000,34.287190,34.287190

In [19]:
X_test, _ = kgfarm.apply_transformation(tranformation_info.iloc[2], X_test)
X_test

Applying StandardScaler transformation
14 feature(s) ['rv1', 'Tdewpoint', 'Visibility', 'Windspeed', 'RH_9', 'lights', 'rv2', 'RH_5', 'RH_4', 'RH_3', 'RH_2', 'RH_1', 'RH_8', 'RH_7'] transformed successfully!

,date,lights,T1,RH_1,T2,RH_2,T3,RH_3,T4,RH_4,T5,RH_5,T6,RH_6,T7,RH_7,T8,RH_8,T9,RH_9,T_out,Press_mm_hg,RH_out,Windspeed,Visibility,Tdewpoint,rv1,rv2
15563,6198,-0.47003,21.200000,-1.735248,0.274447,-2.089435,23.463333,-0.295402,0.489130,-1.654434,19.200000,-1.265191,0.476386,0.000000,0.414366,-2.140597,21.890000,-1.601790,0.405827,-2.950551,0.478518,0.625194,41.833333,0.321843,0.141967,-1.516373,1.186339,1.186339
12564,5005,-0.47003,21.790000,-0.430697,0.250614,0.062244,22.500000,-0.396102,0.534420,-0.245561,20.033333,-0.394779,0.380855,0.397708,0.558967,-0.055324,22.290000,-1.019371,0.594173,-0.290056,0.383459,0.574419,75.000000,-0.017402,0.141967,-0.221893,-0.025274,-0.025274
10649,4238,-0.47003,22.390000,0.292941,0.302211,0.830296,24.500000,0.041283,0.452899,-0.163357,19.390000,-0.306933,0.498829,0.409774,0.547336,-0.224890,22.290000,-0.308795,0.506764,0.125522,0.486574,0.631008,68.000000,0.728935,0.141967,0.168819,-1.480725,-1.480725
16554,6594,-0.47003,24.000000,-2.493940,0.611057,-3.263816,23.390000,-1.769288,0.696558,-1.775455,21.033333,-1.126466,0.772834,0.000000,0.701323,-1.665183,23.272000,-1.599252,0.613944,-1.447279,0.776584,0.713953,31.000000,-0.017402,0.141967,-0.529727,-1.666891,-1.666891
8130,3233,-0.47003,20.050000,-0.494547,0.110565,0.151458,21.100000,-0.609709,0.433877,-0.588074,18.200000,-0.804363,0.179840,0.783552,0.282339,0.133011,20.200000,0.485528,0.271592,-0.640899,0.164339,0.588372,99.000000,-1.238680,-0.535482,-0.908599,0.993441,0.993441
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12861,5111,-0.47003,22.066667,0.135193,0.250614,0.881391,22.890000,0.153172,0.489130,-0.088004,20.000000,-0.459566,0.380855,0.561072,0.594488,0.314226,22.832857,-0.340064,0.542144,-0.145403,0.381847,0.503488,95.000000,-1.035134,-0.323779,0.547692,-0.780249,-0.780249
14687,5834,-0.47003,22.823333,-0.923972,0.479115,-1.415464,27.463333,-0.306591,0.705616,-1.028449,20.730000,-0.975663,0.618852,0.000000,0.616556,-0.923217,23.290000,-0.816984,0.594173,-0.855881,0.588077,0.660078,57.500000,0.796784,0.141967,0.287217,-0.743794,-0.743794
16295,6498,-0.47003,23.100000,-1.507389,0.405405,-1.633633,23.100000,-0.975892,0.693841,-1.236567,21.856667,1.403510,0.405055,0.019885,0.585058,-1.161645,24.290000,-1.184961,0.561915,-1.863428,0.495704,0.838760,57.500000,-0.695890,0.141967,-0.352130,0.239361,0.239361
3369,1332,-0.47003,21.600000,0.578389,0.345700,0.352595,22.500000,1.401245,0.479167,0.690643,19.000000,0.857764,0.222775,0.902562,0.302143,0.553043,22.200000,0.962312,0.357267,1.460165,0.228786,0.851163,90.000000,-0.424494,-1.085910,-0.731002,0.454224,0.454224
14615,5809,-0.47003,22.290000,-0.756209,0.294840,-0.304344,23.500000,-0.429669,0.688406,-0.907754,20.390000,-0.834011,0.466530,0.133401,0.618334,0.201521,22.390000,0.117551,0.568852,-0.320425,0.477981,0.710078,67.333333,-0.017402,-0.634277,0.062262,0.647854,0.647854

### Machine Learning Model

In [ ]:
from sklearn.linear_model import RidgeCV
ridge_cv_model = RidgeCV(alphas=(0.1, 1.0, 10.0),scoring='neg_mean_absolute_error')
ridge_cv_model.fit(X_train,y_train)
y_pred = ridge_cv_model.predict(X_test)

In [20]:
from sklearn.linear_model import Ridge
model = Ridge(alpha=1)

In [21]:
model.fit(X_train,y_train)
y_pred = model.predict(X_test)

In [ ]:
ridge_cv_model.alpha_

In [22]:
import numpy as np
from sklearn.metrics import mean_absolute_error, mean_squared_error
MAE = mean_absolute_error(y_test,y_pred)
MAE

57.11721584761663

In [23]:
MSE = mean_squared_error(y_test,y_pred)
RMSE = np.sqrt(MSE)
RMSE

95.93826306742092